//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAdventureWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long CommentId { get; set; }
        public int UserId { get; set; }
        public string Subject { get; set; }
        public string Comment1 { get; set; }
        public int PhotoId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual photo photo { get; set; }
        public virtual user user { get; set; }
    }
}
